# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email daily report

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Daily report
        body: File('report.txt')
        to: user@example.com
        from: ${{ secrets.MAIL_USERNAME }}
